static k_sensor_ae_info sensor_csi0_ae_info[] = {
    {
        .frame_length = IMX675_VMAX_LINEAR,
        .cur_frame_length = IMX675_VMAX_LINEAR,
        .one_line_exp_time = 0.00001481,
        .gain_accuracy = 1024,
        .min_gain = 1.0,
        .max_gain = 50.0,
        .int_time_delay_frame = 1,
        .gain_delay_frame = 1,
        .color_type = SENSOR_COLOR,
        .integration_time_increment = 0.00001481,
        .gain_increment = IMX675_AGAIN_STEP,
        .max_long_integraion_line = IMX675_VMAX_LINEAR - 4,
        .min_long_integraion_line = 1,
        .max_integraion_line = IMX675_VMAX_LINEAR - 4,
        .min_integraion_line = 1,
        .max_vs_integraion_line = IMX675_VMAX_LINEAR - 4,
        .min_vs_integraion_line = 1,
        .max_long_integraion_time = 0.00001481 * (IMX675_VMAX_LINEAR - 4),
        .min_long_integraion_time = 0.00001481,
        .max_integraion_time = 0.00001481 * (IMX675_VMAX_LINEAR - 4),
        .min_integraion_time = 0.00001481,
        .max_vs_integraion_time = 0.00001481 * (IMX675_VMAX_LINEAR - 4),
        .min_vs_integraion_time = 0.00001481,
        .a_long_gain.min = 1.0,
        .a_long_gain.max = 100.0,
        .a_long_gain.step = (0.3f),
        .a_gain.min = 1.0,
        .a_gain.max = 100.0,
        .a_gain.step = (0.3f),
        .a_vs_gain.min = 1.0,
        .a_vs_gain.max = 100.0,
        .a_vs_gain.step = (0.3f),
        .d_long_gain.max = 1.0,
        .d_long_gain.min = 1.0,
        .d_long_gain.step = (0.3f),
        .d_gain.max = 1.0,
        .d_gain.min = 1.0,
        .d_gain.step = (0.3f),
        .d_vs_gain.max = 1.0,
        .d_vs_gain.min = 1.0,
        .d_vs_gain.step = (0.3f),
    },
};

static const k_sensor_mode sensor_csi0_mode_list[] = {
    {
        .index = 0,
        .sensor_type = IMX675_MIPI_CSI0_2LANE_RAW10_2592X1944_30FPS_LINEAR,
        .size = {
            .bounds_width = 2592,
            .bounds_height = 1944,
            .top = 0,
            .left = 0,
            .width = 2592,
            .height = 1944,
        },
        .fps = 30000,
        .hdr_mode = SENSOR_MODE_LINEAR,
        .bit_width = 10,
        .bayer_pattern = BAYER_PAT_RGGB,
        .mipi_info = {
            .csi_id = 0,
            .mipi_lanes = 2,
            .data_type = 0x2B,
        },
#if defined (CONFIG_MPP_SENSOR_IMX675_ON_CSI0_USE_CHIP_CLK)
        .reg_list = imx675_mipi_2lane_raw10_2592x1944_30fps_mclk_74_25_regs,
        .mclk_setting = {
            {
                .mclk_setting_en = K_TRUE,
                .setting.id = CONFIG_MPP_CSI_DEV0_MCLK_NUM,
                .setting.mclk_sel = SENSOR_PLL1_CLK_DIV4,
                .setting.mclk_div = 16,
            },
            {K_FALSE},
            {K_FALSE},
        },
#else
        .reg_list = imx675_mipi_2lane_raw10_2592x1944_30fps_mclk_74_25_regs,
        .mclk_setting = {
            {K_FALSE},
            {K_FALSE},
            {K_FALSE},
        },
#endif
        .sensor_ae_info = sensor_csi0_ae_info,
    },
};
